### ISSUE TITLE
Failed to execute 'appendChild' on 'Node' from using mapTo operator

### ISSUE THREAD

**Issue by typoerr** [cotttpan/sinkdom#12]
`Uncaught DOMException: Failed to execute 'appendChild' on 'Node': This node type does not support this method.`  in under the case for conditional rendering.

```ts
Observable.merge(
   src$.filter(x => ...).mapTo(/* vnode */),
   src$.filter(x => ...).mapTo(/* vnode */)
)
```

**Comment by cotttpan** [comment]
VNode is update by mutable and vnode.node will be `undefined` by `dispose()` when toggle tree.   

https://github.com/cotttpan/sinkdom/blob/master/src/mount.ts#L95

**Comment by cotttpan** [comment]
I think it is worth looking into using `mapTo` for reuse node.
